### ISSUE TITLE
Malformed HTML being generated

### ISSUE THREAD

**Issue by richplane** [castlegateit/cgit-wp-twitter-redux#2]
Something seems a bit screwy with the HTML we're storing. From the content column of the wp_cgit_twitter :

`RT <a href="https:/twitter.com/AdeBruin_SEI">@AdeBruin_SEI</a>: Are you looking for something to do during summer? Internship available at SEI on the <a href="https:/twitter.com/YCEO_Project">@YCEO_Project</a> <a href="https://york.targetconnect.net/leap/jobSearch.html?id=57937&service=Careers+Service">york.targetconnect.net/leap/jobSearch…</a>a href="https:/twitter.com/YorkEnvironment">@YorkEnvironment</a>`
- bug in the extractContent() function? Are the $entity->starts perhaps being stored (& therefore sorted) as text strings?

**Comment by johnkhughes** [comment]
Fixed when we fixed the multibyte character bug a while back.
